import Colors from '@/src/constants/Color';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffd900',
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 25,
    paddingTop: '11%',
  },
  title: {
    flex: 1,
    textAlign: 'center',
    fontSize: 24,
    fontWeight: 'bold',
    marginLeft: -26,
    color: Colors.primary_background,
  },
  title1: {
    flex: 1,
    textAlign: 'left',
    fontSize: 13,
    marginLeft: 16,
    marginBottom: 10,
    fontWeight: 'bold',
    color: Colors.primary_background,
  },
  backButton: {
    padding: 8,
    fontSize: 26,
    zIndex: 2,
  },
  tableContainer: {
    marginBottom: 20,
    paddingTop: 20,
  },
  tripCard: {
    backgroundColor: '#ffffff',
    padding: 16,
    marginBottom: 10,
    width: '100%',
    alignSelf: 'stretch',
  },
  tripTitle: { fontSize: 16 },
  tripDesc1: { fontSize: 13, color: Colors.blue },
  tripDesc2: { fontSize: 16, color: Colors.primary_background, marginTop: 2 , fontWeight: 'bold'},
  driverAvt: {
    width: 45, 
    height: 45, 
    marginRight: 4, 
    borderRadius: 10, 
    backgroundColor: Colors.background_avatar,
    resizeMode: 'contain', 
  },
  row: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    marginBottom: 10,
  },
  button: {
    backgroundColor: Colors.secondary_background,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
  },
  buttonText: {
    color: Colors.primary_background,
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 14,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noDataText: {
    textAlign: 'center',
    marginTop: 20,
    fontSize: 16,
    color: '#888',
  },
  searchContainer: {
    backgroundColor: '#fff',
    position: 'relative',
    borderTopWidth: 3,
    borderTopColor: '#e7e7e7',
    paddingHorizontal: 16,
  },
  searchInput: {
    height: 50,
    marginVertical: 5,
    borderColor: Colors.secondary_background,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 15,
    backgroundColor: '#f8f8f8',
    fontSize: 16,
  },
  searchLoader: {
    position: 'absolute',
    right: 15,
    top: 15,
  },
  searchResultsContainer: {
    maxHeight: 200,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: '#fff',
    position: 'absolute',
    top: 65, // Position below the search bar
    left: 0,
    right: 0,
    zIndex: 1,
  },
  searchResultItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  filterIcons:{
    width: 16, 
    height: 16, 
    marginLeft: 6,
    marginRight: 3,
  },
  filterLabel: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  tabButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#dbdbdb',
    marginRight: 10,
  },
  activeTabButton: {
    borderWidth: 1,
    borderColor: Colors.secondary_background,
    backgroundColor: '#fffcea',
  },
  createTripButton: {
    backgroundColor: Colors.secondary_background,
    padding: 5,
    borderRadius: 10,
    marginLeft: 8,
    alignItems: 'center',
  },
  createTripButtonText: {
    color: Colors.primary_background,
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 8,
    marginRight: 8,
  },
  driverLink: {
    color: '#535353',
    fontSize: 14,
  },
});

export default styles;
